package api

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"bluei.kr/edge/internal/storage"
)

func postTrace(t *testing.T, s *Server, tankID, suffix string, body map[string]any) *httptest.ResponseRecorder {
	t.Helper()
	b, _ := json.Marshal(body)
	req := httptest.NewRequest(http.MethodPost, "/v1/tanks/"+tankID+suffix, bytes.NewReader(b))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	s.handleTankTraceabilityRoute(w, req)
	return w
}

func getTraceability(t *testing.T, s *Server, tankID string) *httptest.ResponseRecorder {
	t.Helper()
	req := httptest.NewRequest(http.MethodGet, "/v1/tanks/"+tankID+"/traceability", nil)
	w := httptest.NewRecorder()
	s.handleTankTraceabilityRoute(w, req)
	return w
}

// TestStockingLotAutoGenerated — lot_no 미입력 시 LOT-{tank}-{date} 자동 생성, 입식 이벤트/projection 에 반영.
func TestStockingLotAutoGenerated(t *testing.T) {
	s := newTestServerWithApp(t)
	ctx := context.Background()

	w := postStocking(t, s, "tank_01", defaultStockingBody())
	if w.Code != http.StatusOK {
		t.Fatalf("stocking expected 200, got %d: %s", w.Code, w.Body.String())
	}
	var resp map[string]any
	json.Unmarshal(w.Body.Bytes(), &resp)
	lot, _ := resp["lot_no"].(string)
	if lot == "" {
		t.Fatal("expected auto-generated lot_no in stocking response")
	}

	lc, _ := s.store.GetTankLifecycle(ctx, "tank_01")
	if lc == nil || lc.LotNo != lot {
		t.Fatalf("lifecycle lot_no mismatch: got %v want %q", lc, lot)
	}
}

// TestTraceabilityRoundTrip — 입식(lot)→투약→폐사→이동 CTE 가 이벤트로 남고 timeline 에 모인다.
func TestTraceabilityRoundTrip(t *testing.T) {
	s := newTestServerWithApp(t)
	ctx := context.Background()

	// 1) 입식 (명시 lot)
	body := defaultStockingBody()
	body["lot_no"] = "LOT-TEST-001"
	if w := postStocking(t, s, "tank_01", body); w.Code != http.StatusOK {
		t.Fatalf("stocking: %d %s", w.Code, w.Body.String())
	}

	// 2) 투약
	wt := postTrace(t, s, "tank_01", "/treatment", map[string]any{
		"treatment_type": "antibiotic",
		"substance":      "oxytetracycline",
		"dose":           10.0,
		"dose_unit":      "mg/kg",
		"reason":         "예방",
		"operator_id":    "op1",
	})
	if wt.Code != http.StatusOK {
		t.Fatalf("treatment expected 200, got %d: %s", wt.Code, wt.Body.String())
	}
	var tr map[string]any
	json.Unmarshal(wt.Body.Bytes(), &tr)
	if tr["lot_no"] != "LOT-TEST-001" {
		t.Errorf("treatment should attach active lot, got %v", tr["lot_no"])
	}

	// 투약 type 검증 (잘못된 값 → 422)
	if w := postTrace(t, s, "tank_01", "/treatment", map[string]any{
		"treatment_type": "bogus", "substance": "x", "operator_id": "op1",
	}); w.Code != http.StatusUnprocessableEntity {
		t.Errorf("invalid treatment_type expected 422, got %d", w.Code)
	}

	// 3) 폐사
	if w := postTrace(t, s, "tank_01", "/mortality", map[string]any{
		"dead_count": 12, "estimated_cause": "저산소", "operator_id": "op1",
	}); w.Code != http.StatusOK {
		t.Fatalf("mortality expected 200, got %d: %s", w.Code, w.Body.String())
	}

	// 4) 이동 (move 전량 → 출발 transferred, 도착 새 lineage + parent_lot_no)
	wx := postTrace(t, s, "tank_01", "/transfer", map[string]any{
		"transfer_type": "move",
		"to_tank_id":    "tank_02",
		"moved_count":   988,
		"avg_weight_g":  52.0,
		"operator_id":   "op1",
	})
	if wx.Code != http.StatusOK {
		t.Fatalf("transfer expected 200, got %d: %s", wx.Code, wx.Body.String())
	}

	srcLC, _ := s.store.GetTankLifecycle(ctx, "tank_01")
	if srcLC == nil || srcLC.Status != "transferred" {
		t.Errorf("source should be transferred, got %v", srcLC)
	}
	dstLC, _ := s.store.GetTankLifecycle(ctx, "tank_02")
	if dstLC == nil || dstLC.Status != "active" {
		t.Fatalf("dest should be active, got %v", dstLC)
	}
	if dstLC.ParentLotNo != "LOT-TEST-001" {
		t.Errorf("dest parent_lot_no should be source lot, got %q", dstLC.ParentLotNo)
	}
	if dstLC.LotNo == "" || dstLC.LotNo == "LOT-TEST-001" {
		t.Errorf("dest should have its own lot, got %q", dstLC.LotNo)
	}

	// 이벤트 적재 확인
	for _, et := range []string{"tank.treatment.recorded", "tank.mortality.recorded", "tank.transfer.recorded"} {
		evs, _ := s.store.QueryEvents(ctx, storage.EventFilter{EventType: et, Limit: 10})
		if len(evs) < 1 {
			t.Errorf("expected >=1 %s event", et)
		}
	}

	// 5) traceability timeline (tank_01: 입식+투약+폐사+이동 = 4)
	gw := getTraceability(t, s, "tank_01")
	if gw.Code != http.StatusOK {
		t.Fatalf("traceability expected 200, got %d", gw.Code)
	}
	var tl map[string]any
	json.Unmarshal(gw.Body.Bytes(), &tl)
	items, _ := tl["timeline"].([]any)
	if len(items) < 4 {
		t.Errorf("expected >=4 CTE in tank_01 timeline, got %d: %s", len(items), gw.Body.String())
	}
	// 첫 항목은 입식 (시간 오름차순)
	if first, ok := items[0].(map[string]any); ok {
		if first["type"] != "stocking" {
			t.Errorf("timeline should start with stocking, got %v", first["type"])
		}
	}
}
